"""
Export Router - Endpoints for Document and Image Export
========================================================

This router handles exports:
- Complete blueprint documentation (PDF)
- Flowchart images (PNG via Mermaid conversion)

NOTE: The /api/export/flowchart endpoint internally reuses
Mermaid syntax and converts it to image/PDF format.
This shows code reuse, not duplication.

PERSISTENCE: When a blueprint is exported, it's also saved
to Firebase Firestore (if configured).
"""

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
import io
from app.schemas import APIResponse
from app.services import project_service


# Request models for proper JSON body parsing
class BlueprintExportRequest(BaseModel):
    """Request model for exporting a blueprint."""
    project_title: str = Field(..., description="Title of the project")
    idea_input: str = Field(default="", description="Original idea text from the student")
    mode: str = Field(default="ai_only", description="Planning mode used")
    sections: Dict[str, Any] = Field(default={}, description="Blueprint sections")
    user_flow_mermaid: str = Field(default="", description="Mermaid code for user flow")
    tech_stack_mermaid: str = Field(default="", description="Mermaid code for tech stack")


class FlowchartExportRequest(BaseModel):
    """Request model for exporting a flowchart."""
    diagram_type: str = Field(..., description="Type of diagram")
    mermaid_code: str = Field(..., description="Mermaid code for the diagram")
    title: str = Field(default="Flowchart", description="Title for the diagram")


# Create the router
router = APIRouter(
    prefix="/api/export",
    tags=["Export & Download"]
)


@router.post(
    "/blueprint",
    response_model=APIResponse,
    summary="Export complete blueprint",
    description="""
    Generates a complete project documentation package.
    
    Includes all sections:
    - Title and abstract
    - Problem statement
    - Objectives
    - Features
    - System flow
    - Tech stack
    - Architecture
    - Viva guide
    - Pitches
    
    Export format: JSON (frontend converts to PDF)
    
    Also saves the project to Firestore (if configured).
    """
)
async def export_blueprint(request: BlueprintExportRequest):
    """
    Export a complete project blueprint.
    
    The frontend receives JSON and generates the PDF.
    This keeps the backend simple and focused.
    
    Also saves to Firestore for persistence.
    """
    if not request.project_title:
        return APIResponse(
            success=False,
            message="Please provide a project title.",
            data=None,
            errors=["Project title is required"]
        )
    
    sections = request.sections or {}
    
    # Structure the blueprint for export
    import datetime
    blueprint = {
        "projectTitle": request.project_title,
        "generated_at": str(datetime.datetime.now()),
        "sections": sections,
        "export_format": "json",
        "note": "This JSON can be converted to PDF in the frontend using libraries like jsPDF"
    }
    
    # Save to Firestore (non-blocking - continues even if save fails)
    saved_id = None
    if request.idea_input:
        saved_id = await project_service.save_project(
            idea_input=request.idea_input,
            mode=request.mode,
            blueprint=sections,
            user_flow_mermaid=request.user_flow_mermaid,
            tech_stack_mermaid=request.tech_stack_mermaid
        )
    
    return APIResponse(
        success=True,
        message="Blueprint ready for export!" + (" Project saved." if saved_id else ""),
        data={
            "blueprint": blueprint,
            "download_instructions": "Use the frontend PDF generator to create the document",
            "saved_to_database": saved_id is not None,
            "project_id": saved_id
        }
    )


@router.post(
    "/flowchart",
    response_model=APIResponse,
    summary="Export flowchart for download",
    description="""
    Prepares a flowchart for download.
    
    The Mermaid code is returned along with instructions
    for the frontend to render and download as PNG/PDF.
    
    NOTE: This endpoint reuses Mermaid syntax generated by
    other endpoints - it doesn't generate new diagrams.
    """
)
async def export_flowchart(request: FlowchartExportRequest):
    """
    Prepare a flowchart for export.
    
    The actual image generation happens in the frontend
    using Mermaid.js rendering + canvas export.
    """
    valid_types = ["user_flow", "tech_stack", "architecture"]
    
    if request.diagram_type not in valid_types:
        return APIResponse(
            success=False,
            message=f"Invalid diagram type: {request.diagram_type}",
            data=None,
            errors=[f"Valid types are: {', '.join(valid_types)}"]
        )
    
    if not request.mermaid_code:
        return APIResponse(
            success=False,
            message="No diagram code provided.",
            data=None,
            errors=["Generate the flowchart first using the appropriate endpoint"]
        )
    
    return APIResponse(
        success=True,
        message="Flowchart ready for download!",
        data={
            "diagram_type": request.diagram_type,
            "title": request.title,
            "mermaid_code": request.mermaid_code,
            "export_options": {
                "png": "Use mermaid-js in browser to render and export as PNG",
                "pdf": "Render to canvas, then use jsPDF to export as PDF",
                "svg": "Mermaid renders as SVG by default - can be downloaded directly"
            },
            "style_config": {
                "background": "white",
                "theme": "default",
                "fontFamily": "Inter, Arial, sans-serif"
            }
        }
    )


@router.get(
    "/formats",
    response_model=APIResponse,
    summary="Get available export formats",
    description="Returns information about available export formats and requirements."
)
async def get_export_formats():
    """
    Get information about available export formats.
    
    Helps the frontend know what options to show users.
    """
    return APIResponse(
        success=True,
        message="Available export formats:",
        data={
            "document_formats": [
                {
                    "format": "PDF",
                    "description": "Complete project documentation",
                    "generated_by": "Frontend using jsPDF",
                    "recommended_for": "Reports, submissions"
                },
                {
                    "format": "JSON",
                    "description": "Raw blueprint data",
                    "generated_by": "Backend directly",
                    "recommended_for": "Backup, further processing"
                }
            ],
            "diagram_formats": [
                {
                    "format": "PNG",
                    "description": "Flowchart image",
                    "generated_by": "Frontend Mermaid rendering",
                    "recommended_for": "Presentations, reports"
                },
                {
                    "format": "SVG",
                    "description": "Vector flowchart",
                    "generated_by": "Frontend Mermaid rendering",
                    "recommended_for": "High-quality printing"
                },
                {
                    "format": "PDF",
                    "description": "Flowchart document",
                    "generated_by": "Frontend canvas + jsPDF",
                    "recommended_for": "Professional documents"
                }
            ]
        }
    )
